package com.izatec.pay.core.comum;

public enum PagamentoModelo {
    UNICO,//GERAÇÃO DE UM UNICO PAGAMENTO
    RECORRENTE,//SEM DATA DE ENCERRAMENTO - A PESSOA PRECISA ENCERRAR O CONTRATO
    PROGRAMADO, //ENCERRAMENTO COM BASE NO TOTAL DE PARCELAS,
    PARCELADO,//PAGA O VALOR TOTAL E DIVIDE AS PARCELAS

}
