package com.izatec.pay.core.comum;

public enum Status {
    ATIVA, //GERANDO PARCELAS
    FINALIZADA,//QUANDO TODAS AS PARCELAS FORAM GERADAS
    QUITADA, //QUANDO A COBRANÇA MODELO PARCELADO NÃO TEM MAIS PARCELAS
    ENCERRADA, //QUANDO A COBRANÇA MODELO RECORRENTE ou PARCELADO NAO DEVE MAIS GERAR PARCELAS
}
